version: 2
jobs:
  build:
    docker:
      - image: mikicz/tox
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DB_USER: root
          DB_NAME: circle_test
          DB_PASSWORD: "password"
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: "password"
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libpq-dev
      - run: tox
