version: 2
jobs:
  build:
    docker:
      - image: mikicz/tox
        environment: # environment variables for primary container
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DB_USER: root
          DB_NAME: circle_test
          DB_PASSWORD: "password"
      - image: circleci/postgres:10 # an example of how to specify a service container
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: "password"
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libpq-dev
      - run: tox
